'use client'

import { useEffect, useMemo, useState } from 'react'
import { Bot, Code2, Loader2, Sparkles, Wand2 } from 'lucide-react'
import { cn } from '@/lib/utils'

type DemoScenario = {
  id: string
  title: string
  description: string
  prompt: string
  codeBefore: string
  codeAfter: string
  highlights: string[]
}

const SCENARIOS: DemoScenario[] = [
  {
    id: 'refactor-api',
    title: 'Hardening an API handler',
    description: 'Ask DevFlowHub to refactor an API route for better validation and logging.',
    prompt: `Refactor this handler to add input validation and structured logging.`,
    codeBefore: `export async function POST(req: NextRequest) {
  const body = await req.json()
  const user = await prisma.user.create({ data: body })
  return NextResponse.json(user)
}
`,
    codeAfter: `export async function POST(req: NextRequest) {
  try {
    const body = await req.json()

    const payload = validatePayload(body) // zod schema generated by AI
    const user = await prisma.user.create({ data: payload })

    logger.info({ userId: user.id }, 'User created')
    return NextResponse.json(user, { status: 201 })
  } catch (error) {
    logger.error({ error }, 'Failed to create user')
    return NextResponse.json({ error: 'Invalid payload' }, { status: 400 })
  }
}
`,
    highlights: [
      'Generated validation helper with Zod',
      'Added structured logging and status codes',
      'Handled errors without leaking stack traces',
    ],
  },
  {
    id: 'component',
    title: 'Instant component redesign',
    description: 'Upgrade a legacy React component to modern patterns and accessibility.',
    prompt: `Modernize this dashboard card with Tailwind, ARIA labels, and responsive layout.`,
    codeBefore: `const StatsCard = (props) => {
  return (
    <div className="card">
      <h3>{props.title}</h3>
      <p>{props.value}</p>
    </div>
  )
}
`,
    codeAfter: `export function StatsCard({ title, value, trend }: Props) {
  return (
    <article
      className="group rounded-2xl border border-white/5 bg-gradient-to-br from-slate-900/60 to-slate-900/20 px-6 py-5 shadow-xl shadow-black/30 transition hover:border-accent-warn/40 hover:shadow-accent-warn/20"
      aria-label={\`Metric \${title}\`}
    >
      <div className="flex items-center justify-between gap-4">
        <span className="text-sm font-medium text-slate-400">{title}</span>
        <span className={cn(
          'rounded-full px-2 text-xs font-medium',
          trend > 0 ? 'bg-green-500/15 text-green-400' : 'bg-slate-700/40 text-slate-300'
        )}>
          {trend > 0 ? '+' : ''}{trend}%
        </span>
      </div>
      <p className="mt-2 text-3xl font-semibold tracking-tight text-white">{value}</p>
    </article>
  )
}
`,
    highlights: [
      'Applied semantic article + ARIA label',
      'Responsive Tailwind styling with gradients',
      'Context-aware trend badge suggested by AI',
    ],
  },
  {
    id: 'tests',
    title: 'Generate integration tests',
    description: 'Turn a product spec into comprehensive Playwright coverage.',
    prompt: `Write Playwright tests that cover happy path and validation errors for the workspace wizard.`,
    codeBefore: `// spec: workspace wizard collects
// name, framework, ai mode
// invalid name -> error toast
// submit -> API POST /api/workspaces`,
    codeAfter: `test.describe('Workspace Wizard', () => {
  test('creates workspace successfully', async ({ page }) => {
    await page.goto('/dashboard')
    await page.getByRole('button', { name: 'New Project' }).click()
    await page.getByLabel('Project name').fill('Marketing Site')
    await page.getByLabel('Framework').selectOption('Next.js')
    await page.getByRole('button', { name: 'Enable multi-file AI' }).click()

    const response = page.waitForResponse('/api/workspaces')
    await page.getByRole('button', { name: 'Create workspace' }).click()
    expect((await response()).status()).toBe(201)
  })

  test('shows validation error for empty name', async ({ page }) => {
    await page.goto('/dashboard')
    await page.getByRole('button', { name: 'New Project' }).click()
    await page.getByRole('button', { name: 'Create workspace' }).click()
    await expect(page.getByText('Project name is required')).toBeVisible()
  })
})
`,
    highlights: [
      'Expands product spec into runnable tests',
      'Auto-infers selectors from UI accessibility',
      'Covers both happy path and validation errors',
    ],
  },
]

export default function HeroInteractiveDemo() {
  const [activeScenario, setActiveScenario] = useState<DemoScenario>(SCENARIOS[0])
  const [isRunning, setIsRunning] = useState(false)
  const [showResult, setShowResult] = useState(false)

  useEffect(() => {
    setShowResult(false)
    const timeout = setTimeout(() => {
      setShowResult(true)
    }, 800)
    return () => clearTimeout(timeout)
  }, [activeScenario])

  const handleRun = () => {
    setIsRunning(true)
    setShowResult(false)
    setTimeout(() => {
      setIsRunning(false)
      setShowResult(true)
    }, 900)
  }

  const codeBeforeLines = useMemo(() => activeScenario.codeBefore.trim().split('\n'), [activeScenario])
  const codeAfterLines = useMemo(() => activeScenario.codeAfter.trim().split('\n'), [activeScenario])

  return (
    <div className="relative overflow-hidden rounded-2xl sm:rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900/90 via-slate-900/60 to-slate-900/20 p-1 shadow-2xl shadow-black/40">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(249,115,22,0.08),_transparent_55%)]" />
      <div className="relative grid gap-4 sm:gap-6 p-4 sm:p-6 md:grid-cols-[280px,1fr] lg:grid-cols-[320px,1fr]">
        {/* Scenario selector */}
        <div className="space-y-3 sm:space-y-4">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-orange-200/70">
            <Sparkles className="h-4 w-4 text-accent-warn" />
            <span>Try DevFlowHub</span>
          </div>
          <p className="text-xs sm:text-sm text-slate-400 leading-relaxed">
            Choose a real workflow and run the AI. This is a sandboxed preview – the live product goes even deeper with workspace-wide context.
          </p>

          <div className="space-y-2 sm:space-y-3">
            {SCENARIOS.map((scenario) => (
              <button
                key={scenario.id}
                onClick={() => {
                  setActiveScenario(scenario)
                  setIsRunning(false)
                }}
                className={cn(
                  'w-full rounded-xl sm:rounded-2xl border px-3 sm:px-4 py-2.5 sm:py-3 text-left transition-all duration-200',
                  scenario.id === activeScenario.id
                    ? 'border-accent-warn/60 bg-accent-warn/10 text-white shadow-lg shadow-orange-500/10'
                    : 'border-white/5 bg-white/5 text-slate-300 hover:border-accent-warn/30 hover:bg-accent-warn/5'
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-xs sm:text-sm font-semibold">{scenario.title}</span>
                  <Wand2 className="h-3.5 w-3.5 sm:h-4 sm:w-4 flex-shrink-0 text-accent-warn" />
                </div>
                <p className="mt-1 text-[11px] sm:text-xs text-slate-400 line-clamp-2">{scenario.description}</p>
              </button>
            ))}
          </div>
        </div>

        {/* Demo pane */}
        <div className="rounded-xl sm:rounded-2xl border border-white/10 bg-slate-950/40 backdrop-blur-xl">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 sm:gap-0 border-b border-white/5 px-3 sm:px-4 py-2.5 sm:py-3">
            <div className="flex items-center gap-1.5 sm:gap-2 text-[10px] sm:text-xs uppercase tracking-widest text-slate-400">
              <Bot className="h-3.5 w-3.5 sm:h-4 sm:w-4 text-accent-warn flex-shrink-0" />
              <span className="truncate">Context aware AI pair-programmer</span>
            </div>
            <button
              aria-label="Run AI demo"
              onClick={handleRun}
              className="inline-flex items-center gap-1.5 sm:gap-2 rounded-full bg-accent-warn px-2.5 sm:px-3 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold text-white transition hover:bg-orange-500 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-900 focus-visible:ring-accent-warn w-full sm:w-auto justify-center"
            >
              {isRunning ? (
                <>
                  <Loader2 className="h-3 w-3 sm:h-3.5 sm:w-3.5 animate-spin" />
                  Thinking…
                </>
              ) : (
                <>
                  <Sparkles className="h-3 w-3 sm:h-3.5 sm:w-3.5" />
                  Run the AI
                </>
              )}
            </button>
          </div>

          <div className="grid gap-3 sm:gap-4 px-3 sm:px-4 py-3 sm:py-5 md:grid-cols-2">
            <div className="space-y-2 sm:space-y-2">
              <div className="flex items-center justify-between text-[10px] sm:text-xs font-semibold uppercase tracking-widest text-slate-400">
                <span>Prompt</span>
                <Code2 className="h-3.5 w-3.5 sm:h-4 sm:w-4 text-slate-500" />
              </div>
              <div className="rounded-lg sm:rounded-xl border border-white/5 bg-slate-900/80 p-2.5 sm:p-3 text-xs sm:text-sm text-slate-300 shadow-inner shadow-black/40">
                {activeScenario.prompt}
              </div>

              <div className="rounded-lg sm:rounded-xl border border-white/5 bg-slate-900/80 pb-2 sm:pb-3">
                <div className="flex items-center justify-between border-b border-white/5 px-2.5 sm:px-3 py-1.5 sm:py-2 text-[10px] sm:text-xs text-slate-400">
                  <span>Source code</span>
                  <span>Before</span>
                </div>
                <pre className="max-h-48 sm:max-h-72 overflow-x-auto overflow-y-auto px-2.5 sm:px-3 py-2 sm:py-3 text-[10px] sm:text-[12px] leading-relaxed text-slate-200">
{codeBeforeLines.map((line, index) => (
  <code key={index} className="block text-left whitespace-pre-wrap break-words">
    <span className="mr-1.5 sm:mr-2 text-slate-600 inline-block">{String(index + 1).padStart(2, '0')}</span>
    <span className="break-all">{line}</span>
  </code>
))}
                </pre>
              </div>
            </div>

            <div className="space-y-2.5 sm:space-y-3">
              <div className="rounded-lg sm:rounded-xl border border-white/5 bg-slate-900/80 pb-2 sm:pb-3">
                <div className="flex items-center justify-between border-b border-white/5 px-2.5 sm:px-3 py-1.5 sm:py-2 text-[10px] sm:text-xs text-emerald-300/80">
                  <span>AI suggestion</span>
                  <span className="text-[9px] sm:text-[10px]">
                    {showResult ? 'Ready to apply' : isRunning ? 'Analyzing project…' : 'Preview'}
                  </span>
                </div>

                <div className="relative">
                  {!showResult && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-slate-950/80 backdrop-blur-sm z-10">
                      <Loader2 className="h-4 w-4 sm:h-5 sm:w-5 animate-spin text-accent-warn" />
                      <span className="text-[10px] sm:text-xs text-slate-400">Reading workspace context…</span>
                    </div>
                  )}

                  <pre className="max-h-48 sm:max-h-72 overflow-x-auto overflow-y-auto px-2.5 sm:px-3 py-2 sm:py-3 text-[10px] sm:text-[12px] leading-relaxed text-emerald-200 transition-opacity duration-300">
{codeAfterLines.map((line, index) => (
  <code key={index} className="block text-left whitespace-pre-wrap break-words">
    <span className="mr-1.5 sm:mr-2 text-emerald-600 inline-block">{String(index + 1).padStart(2, '0')}</span>
    <span className="break-all">{line}</span>
  </code>
))}
                  </pre>
                </div>
              </div>

              <div className="rounded-lg sm:rounded-xl border border-white/5 bg-white/5 p-2.5 sm:p-3 text-[10px] sm:text-xs text-slate-200">
                <p className="mb-1.5 sm:mb-2 font-semibold uppercase tracking-widest text-slate-400">Why this matters</p>
                <ul className="space-y-1 sm:space-y-1.5">
                  {activeScenario.highlights.map((item) => (
                    <li key={item} className="flex items-start gap-1.5 sm:gap-2">
                      <span className="mt-0.5 sm:mt-1 h-1 w-1 sm:h-1.5 sm:w-1.5 flex-shrink-0 rounded-full bg-accent-warn" />
                      <span className="break-words">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

